# Generated by Django 4.2.25 on 2025-10-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_important', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
